#! /usr/bin/python3

import sys

num = sys.argv[1:]

def Average():
    total = sum(int(i) for i in num)
    count = len(num)
    avg = total / count


    print('average of the ', count, 'is: ', int(avg))

Average()